# Build and check LPub3D on Linux and macOS
# Trevor SANDY <trevor.sandy@gmail.com>
# Last Update: May 04, 2021
# Copyright (c) 2017 - 2023 by Trevor SANDY
#

# The following variables can be set to true from
# Travis-CI Site->More Options->Settings->Environment Variables
#
# LDV_SKIP_TRAVIS_VAR     ; skip Travis-CI build 

os: linux

dist: xenial

language: cpp

git:
  depth: false

branches:
  only:
  - lpub3d-build

addons:
  apt:
    packages:
    - libosmesa6-dev
    - libtinyxml-dev
    - libgl2ps-dev
    - libjpeg-dev

cache:
  ccache: true
  directories:
  - ${HOME}/ldraw
  - ${HOME}/Library/ldraw

jobs:
  fast_finish: true
  include:
  - os: linux
    dist: bionic
    compiler: gcc
    env:
     - QT_BASE=515
  - os: osx
    osx_image: xcode11.3
    compiler: clang
    env:
     - QT_BASE=515

before_install:
  # Skip build if the commit message contains [skip travis] or [travis skip]
  # or environment variable LP3D_SKIP_TRAVIS_VAR is true
  - >
      echo "$TRAVIS_COMMIT_MESSAGE" | awk '{print tolower($0)}' | grep -E '\[(skip travis|travis skip)\]'
      && echo "[skip travis] detected, exiting."
      && exit 0 || [ "$LDV_SKIP_TRAVIS_VAR" = "true" ]
      && echo "'Skip Travis-CI' build detected in environment variable, exiting."
      && exit 0 || true
  # Build package if commit message contains [build pkg]
  - >
      echo "$TRAVIS_COMMIT_MESSAGE" | awk '{print tolower($0)}' | grep -E '\[build pkg.*\]'
      && echo "[build pkg] detected."
      && export LDV_BUILD_PKG=yes || true
  # Build and deploy package if commit message contains [deploy pkg]
  - >
      echo "$TRAVIS_COMMIT_MESSAGE" | awk '{print tolower($0)}' | grep -E '\[deploy pkg\]'
      && echo "[deploy pkg] detected."
      && export LDV_BUILD_PKG=yes
      && export LDV_DEPLOY_PKG=yes || true
  # Add private qt repositories
  - if [[ "$QT_BASE" = "515" && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt-5.15.2-$TRAVIS_DIST -y; fi
  # Update repository index and download package dependencies/docker-engine if required
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo apt-get update -qq; 
      sudo apt-get install libglu1-mesa-dev libosmesa6-dev libgl2ps-dev libtinyxml-dev;
      export LDV_DIST_DIR=lpub3d_linux_3rdparty;
      export LDRAWDIR=${HOME}/ldraw;
    else
      brew install ccache tinyxml gl2ps libjpeg minizip;
      export PATH="/usr/local/opt/ccache/libexec:$PATH";
      export LDV_DIST_DIR=lpub3d_macos_3rdparty;
      export LDRAWDIR=${HOME}/Library/ldraw;
    fi

install:
  # Install qt5 on Linux
  - if [[ "$QT_BASE" = "515" && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo apt-get install -qq qt${QT_BASE}base; source /opt/qt${QT_BASE}/bin/qt${QT_BASE}-env.sh; fi
  # Install qt5 on MacOS, clone lpub3d_macos_3rd party repository and download LDraw library archive files
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew install qt5;
      brew link --force qt5;
    fi
  # Install ldraw library
  - if [ ! -d ${LDRAWDIR}/parts ]; then
      if [ "$TRAVIS_OS_NAME" = "osx" ]; then LDRAWDIR_ROOT=${HOME}/Library; else LDRAWDIR_ROOT=${HOME}; fi;
      echo "LDraw library not found at ${LDRAWDIR}. Downloading library...";
      curl -s -O http://www.ldraw.org/library/updates/complete.zip;
      echo "Extracting LDraw library into ${LDRAWDIR}...";
      unzip -d ${LDRAWDIR_ROOT} -q complete.zip;
      if test -d ${LDRAWDIR}; then echo "LDraw library extracted, LDRAWDIR defined."; fi;
    fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      echo "set LDRAWDIR in environment.plist...";
      ./set-ldrawdir.command;
      grep -A1 -e 'LDRAWDIR' ~/.MacOSX/environment.plist;
      echo "LDRAWDIR......${LDRAWDIR}";
      echo "set LDRAWDIR Completed.";
    fi

script:
  # Compile and install - this will be the MacOS logic, linux will move to Docker
  - qmake -v
  - qmake CONFIG+=3RD_PARTY_INSTALL=../${LDV_DIST_DIR} CONFIG+=release CONFIG+=BUILD_CUI_ONLY CONFIG+=USE_SYSTEM_LIBS CONFIG+=BUILD_CHECK
  - make && make install

before_deploy:
  # create a tarball of the lpub3d_linux_3rdparty folder
  - if [ "$LDV_BUILD_PKG" = "yes" ]; then
      if [ -d ${LDV_DIST_DIR} ]; then
        tar -czf ${LDV_DIST_DIR}.tar.gz ${LDV_DIST_DIR} && echo "Tarball ${LDV_DIST_DIR}.tar.gz created.";
      fi;
    fi

deploy:
  provider: releases
  token:
    secure: 7Rd6ucWhoORZo5v3kjilzCH7GWpA+ncVmyskqdjFoIqFa+VECyeSLJdOLZIZxZYTdqSHkvgRNxmUMZJI2rGFdkbEcGJ9BMRls4ClKL1OA5TU9ZAGIrbpG2Rl+lwmmqfBSupjAOSAabL5fn8NuxOqDyjjmHChZPPIdJwnP/dt3DaW0bbWnFvOCOVRbQx/cydJ31VFwXrTyqdVHbM2J3HgXEqqzEnuMZMht39983SZM2uzf7JcqyRfKC5YW87ykGGB3BmE0tQBsrLQSDJlcOskqVheIuqkOOG81ci1cz62vskVuWAEZd/hlZ8luAm/7VkMQO1KvuxKBRqDfDZb5DCJ2nIh2fN7dO3jirrFXQiEILAa823qPpCIonI+TZOyfqsnNZLTlglZ62rtcXH/7Tj+nQfC7WX057lT7bTxgf1epkPYyIdXpiqPFUhHXHSbEnDfDgvoBeGGgUcriM1GkIXBvpw0dk5IdRj7r7sda3T9ZoFMaYuk48WfBmVqoRYjFOfCoAPV3a654EvRA6cIKdLn5yFlK+z1geUb6FiVyPKTi6MXpCVDe99/qqxSMwm6nQtRfXp8PM/pkZmO8rSh88bH5ql0Jh8mfPPxQkDL0wz/tLh54szBj0mTi0/AKzYHkeO/EUkkp+Jtl9pU5VZUBtTzheFZsa+nBwUcGwPPhIgUwzw=
  file: ${LDV_DIST_DIR}.tar.gz
  overwrite: true
  name: ${LDV_DIST_DIR}
  release_notes: 'LDView - `uname` archive package of LPub3D image renderer'
  prerelease: true
  cleanup: false
  edge: true  # opt in to dpl v2
  on:
    repo: trevorsandy/ldview
    branch: lpub3d-build
    condition: $LDV_DEPLOY_PKG = yes

notifications:
  email:
    on_success: never
    on_failure: always
