# Build and check LDView x86 and x86_64 architectures unsing MSBuild
version: LDView-AV-4.3.0.{build}

clone_folder: c:\projects\ldview

cache:
 - '$(APPVEYOR_BUILD_FOLDER)\ldraw'

shallow_clone: true

branches:
  only:
   - qmake-build

#image: Visual Studio 2017

skip_commits:
  files:
    - QT/
    - MacOSX/
    - OSMesa/

matrix:
  fast_finish: true

environment:
  LP3D_DIST_DIR: lpub3d_windows_3rdparty
  LP3D_DIST_DIR_PATH: $(APPVEYOR_BUILD_FOLDER)\$(LP3D_DIST_DIR)

init:
 - ps: write-host "Building LDView x86 and x86_64 architectures..."
 - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
 - ps: |
      If ($env:APPVEYOR_REPO_COMMIT_MESSAGE.ToLower().Contains("[build pkg]")) {
        write-host "[build pkg] detected."
        $env:LDV_BUILD_PKG = "yes"
      }
 - ps: |
      If ($env:APPVEYOR_REPO_COMMIT_MESSAGE.ToLower().Contains("[deploy pkg]")) {
        write-host "[deploy pkg] detected."
        $env:LDV_BUILD_PKG = "yes"
        $env:LDV_DEPLOY_PKG = $true
      }

build_script:
 - ps: |
      write-host "  Distribution directory..[$env:LP3D_DIST_DIR_PATH]"
      write-host "  Working Directory.......[$PWD]"
      If ($env:LDV_BUILD_PKG -eq "yes") {
        cmd.exe /c build.cmd -all -ins -chk -minlog 2`>`&1
        $env:LDV_ARTEFACT_ITEM_COUNT = (Get-ChildItem -Path $env:LP3D_DIST_DIR_PATH -Recurse).count
        write-host "`n  Artifact count....[$env:LDV_ARTEFACT_ITEM_COUNT]"
      } Else {
        cmd.exe /c build.cmd -all -chk -minlog 2`>`&1
      }

test: off

after_build:
 - ps: |
      If (($env:LDV_BUILD_PKG -eq "yes") -and ([int]$env:LDV_ARTEFACT_ITEM_COUNT -gt 5)) {
        cd $env:APPVEYOR_BUILD_FOLDER; write-host "Creating zip archive artefact from ./$env:LP3D_DIST_DIR..."
        7z a -tzip $env:LP3D_DIST_DIR $env:LP3D_DIST_DIR | Select-String -Pattern '(^Creating)|(^Everything)' -CaseSensitive; write-host "Zip archive $env:LP3D_DIST_DIR.zip created."
        $root = Resolve-Path $env:APPVEYOR_BUILD_FOLDER; [IO.Directory]::GetFiles($root.Path, '*.zip', 'TopDirectoryOnly') | % { Push-AppveyorArtifact $_ -Type zip -FileName $_.Substring($root.Path.Length + 1) -DeploymentName $env:LP3D_DIST_DIR}
      }

deploy:
 - provider: GitHub
   repository: trevorsandy/ldview
   description: 'LDView - Windows archive package of LPub3D image renderer'
   auth_token:
     secure: rnf4qpF81ISjm8q13OgkAaoKZReXpjODhU9fbGFMhMydHrda1ezLubGXRU9OKGu4
   release: $(LP3D_DIST_DIR)
   artifact: $(LP3D_DIST_DIR).zip
   prerelease: true
   force_update: true
   on:
    branch: qmake-build
    ldv_deploy_pkg: true
