version: LDView-AV-4.3.0.{build}

clone_folder: c:\projects\ldview

cache:
 - 'C:\projects\ldraw'
 - 'C:\projects\complete.zip'

shallow_clone: true

branches:
  only:
   - qmake-build

image: Visual Studio 2017

skip_commits:
  files:
    - QT/
    - MacOSX/
    - OSMesa/

matrix:
  fast_finish: true

environment:
  LDV_DIST_DIR: lpub3d_windows_3rdparty
  LDV_LDRAW_ROOT: c:\projects
  LDV_DIST_DIR_PATH: $(APPVEYOR_BUILD_FOLDER)\$(LDV_DIST_DIR)

init:
 - ps: write-host "Building LDView x86 and x86_64 architectures..."
 - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
 - ps: |
      If ($env:APPVEYOR_REPO_COMMIT_MESSAGE.ToLower().Contains("[build pkg]")) {
        write-host "[build pkg] detected."
        $env:LDV_BUILD_PKG = "yes"
      }
 - ps: |
      If ($env:APPVEYOR_REPO_COMMIT_MESSAGE.ToLower().Contains("[deploy pkg]")) {
        write-host "[deploy pkg] detected."
        $env:LDV_BUILD_PKG = "yes"
        $env:LDV_DEPLOY_PKG = $true
      }

build_script:
 - ps: |
      write-host "  Build directory.....[$env:LDV_DIST_DIR_PATH]"
      write-host "  Working Directory...[$PWD]"
      If ($env:LDV_BUILD_PKG -eq "yes") {
        cmd.exe /c build.cmd -all -ins -chk
        $env:LDV_ARTEFACT_ITEM_COUNT = (Get-ChildItem -Path $env:LDV_DIST_DIR_PATH -Recurse).count
        write-host "`n  Artifact count....[$env:LDV_ARTEFACT_ITEM_COUNT]"
      } Else {
        cmd.exe /c autobuild.cmd -all -chk
      }

test: off

after_build:
 - ps: |
      If (($env:LDV_BUILD_PKG -eq "yes") -and ([int]$env:LDV_ARTEFACT_ITEM_COUNT -gt 5)){
        cd $env:APPVEYOR_BUILD_FOLDER; write-host "Creating single tarball artefact from ./$env:LDV_DIST_DIR..."
        bash -lc "tar -czvf lpub3d_windows_3rdparty.tar.gz ./lpub3d_windows_3rdparty && echo Tarball lpub3d_windows_3rdparty.tar.gz created."
        $root = Resolve-Path $env:APPVEYOR_BUILD_FOLDER; [IO.Directory]::GetFiles($root.Path, '*.tar.gz', 'TopDirectoryOnly') | % { Push-AppveyorArtifact $_ -FileName $_.Substring($root.Path.Length + 1) -DeploymentName $env:LDV_DIST_DIR}
      }

deploy:
 - provider: GitHub
   repository: trevorsandy/ldview
   description: 'LDView - Windows archive package of LPub3D image renderer'
   auth_token:
     secure: rnf4qpF81ISjm8q13OgkAaoKZReXpjODhU9fbGFMhMydHrda1ezLubGXRU9OKGu4
   release: $(LDV_DIST_DIR)
   artifact: $(LDV_DIST_DIR).tar.gz
   prerelease: true
   force_update: true
   on:
    branch: qmake-build
    pov_deploy_pkg: true
