version: '3.4'
services:
  ldview-fedora:
    build:
      context: .
      dockerfile: Dockerfile-fedora_latest
    restart: "no"
    volumes:
      - .:/mnt/lego
  ldview-debian:
    build:
      context: .
      dockerfile: Dockerfile-debian_latest
    restart: "no"
    volumes:
      - .:/mnt/lego
  ldview-ubuntu:
    build:
      context: .
      dockerfile: Dockerfile-ubuntu_22.04
    restart: "no"
    volumes:
      - .:/mnt/lego
  ldview-arch:
    build:
      context: .
      dockerfile: Dockerfile-arch
    restart: "no"
    volumes:
      - .:/mnt/lego
  ldview-opensuse:
    build:
      context: .
      dockerfile: Dockerfile-opensuse_latest
    restart: "no"
    volumes:
      - .:/mnt/lego
  ldview-appimage:
    build:
      context: .
      dockerfile: Dockerfile-appimage
    restart: "no"
    volumes:
      - .:/mnt/lego
