<<<<<<<< HEAD:QT/docker/Dockerfile-mageia_6
FROM mageia:6
MAINTAINER Peter Bartfai pbartfai@stardust.hu

ARG LDVIEW_BRANCH=master
ADD install-devel-packages.sh /
RUN ./install-devel-packages.sh

VOLUME /mnt/lego
ENV PATH /usr/lib64/qt4/bin:$PATH
CMD cd ldview/QT ; \
	git pull; \
	PATH=/usr/lib64/qt5/bin:$PATH ;\
	export PATH ;\
	./makerpm
========
FROM ubuntu:latest
MAINTAINER Peter Bartfai pbartfai@stardust.hu

ARG LDVIEW_BRANCH=master
ENV DEBIAN_FRONTEND=noninteractive
ADD install-devel-packages.sh /
RUN ./install-devel-packages.sh

VOLUME /mnt/lego
CMD cd ldview/QT ; \
	git pull; \
	sed -i 's/kdelibs5-dev//g' debian/control ; \
	./makedeb -qt5
>>>>>>>> c633bf09 (Docker: Ubuntu update):QT/docker/Dockerfile-ubuntu_latest
